
mybatis:
  type-aliases-package: gov.usgs.wma.mlrlegacy
  type-handlers-package: gov.usgs.wma.mlrlegacy
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    aggressive-lazy-loading: false
  mapper-locations: "classpath:monitoringLocation.xml"

spring:
  datasource:
    url: "jdbc:postgresql://${mlrLegacyDbHost}:${mlrLegacyDbPort}/mlr_legacy"
    username: ${mlrLegacyDataUsername}
    password: ${mlrLegacyDataPassword}
    driver-class-name: org.postgresql.Driver

security:
  require-ssl: true
  basic:
    enabled: false
  oauth2:
    resource:
      filter-order: 3
      jwt:
        keyUri: ${authPublicKeyUrl}
  maintenanceRoles: ${maintenanceRoles}

server:
  port: ${serverPort:8443}
  ssl:
    key-store: ${keystoreLocation}
    key-store-password: ${keystorePassword}
    key-password: ${keystorePassword}
    key-alias: ${keystoreSSLKey:tomcat}

logging:
  level:
    org:
      springframework: ${springFrameworkLogLevel}
